kentcdodds/kcd-scripts

src/scripts/__tests__/__snapshots__/travis-after-success.js.snap
src/scripts/__tests__/travis-after-success.js
src/scripts/travis-after-success.js
src/utils.js

I'm really only making a PR to test it out... I'm not quite to the point where I'm ready to make this a real package that people depend on and want good management of 😅

feat(travis-after-success): be smarter about when to try the autorelease script

---

src/scripts/__tests__/__snapshots__/travis-after-success.js.snap
src/scripts/__tests__/travis-after-success.js
src/scripts/travis-after-success.js

**What**:
Skips running `codecov` if `SKIP_CODECOV=true` environment variable is set
**Why**:
In our CI environment (self-hosted jenkins), we monitor coverage ourselves and can't even access codecov.io
**How**:
In the travis-after-success.js script, we check not only the existence of `coverage`, but now also make sure `SKIP_CODECOV` is not true.
**Checklist**:

feat: Add ability to skip codecov

---

README.md

**What**:
Removing CodeSponsor link
**Why**:
Code Sponsor is down and its link is broken.
**How**:
Removed its link in README :)
**Checklist**:

Remove CodeSponsor

---

.all-contributorsrc
README.md
src/scripts/__tests__/__snapshots__/lint.js.snap
src/scripts/__tests__/__snapshots__/test.js.snap
src/scripts/__tests__/helpers/serializers.js
src/scripts/__tests__/lint.js
src/scripts/__tests__/test.js

**What**:
I've been building [my own version of kcd-scripts](https://github.com/macklinu/mdu-scripts) and using this codebase as a guideline for how to structure things, write tests, etc. In the process of studying this codebase, I noticed a few typos in test names + a comment.
**Why**:
Just wanting to contribute back something to this project!
**How**:
I updated the `lint.js` and `test.js` test cases to use the name `lint` and `test` respectively and updated the Jest snapshots.
**Checklist**:
Thanks! 😄

test: fix typos

---

src/config/rollup.config.js

Treat imported subdirectories/files from packages as external too

---

src/config/rollup.config.js

fix(rollup): fix predicate function for empty external lists

---

src/config/lintstagedrc.js
src/scripts/__tests__/__snapshots__/format.js.snap
src/scripts/format.js

**What**: Format tsx files as discussed in https://github.com/paypal/downshift/pull/373
**Why**: N/A
**How**: N/A
**Checklist**:

Format tsx files

---

.all-contributorsrc
README.md
src/config/babelrc.js

**What**: Update pragma for preact from `'h'` to `'React.h'` where `React` is an alias for preact
**Why**: https://github.com/kentcdodds/kcd-scripts/issues/50
**How**: Update .babelrc
**Checklist**:

Update pragma for preact build

---

.all-contributorsrc
README.md
src/config/jest.config.js

**What**:
Fixes the `SecurityError: localStorage is not available for opaque origins` error. Relevant issue https://github.com/facebook/jest/issues/6766
**Why**:
Tests won't work otherwise
**How**:
Adding a `testURL` property to the `jest.config.js`
**Checklist**:

Fix Jest by adding testURL property to config

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
other/CODE_OF_CONDUCT.md
other/MAINTAINING.md
src/scripts/build/rollup.js

**What**:
Formatting
**Why**:
To use the latest formatting by Prettier
**How**:
Just ran `npm run format` 
**Checklist**:

style: Update prettier formatting

---

src/config/rollup.config.js

I think the change is self-explanatory, if not please ping me and I'll explain in more details

fix: default external should include regular deps

---

src/scripts/__tests__/__snapshots__/travis-after-success.js.snap
src/scripts/travis-after-success.js

**What**:
Upgrade `travis-deploy-once` to the latest version
**Why**:
Keeping up-to-date
**How**:
Bumping version. The only major change from v4 is that they dropped node v6 support, which should not be a problem in our case. 
**Checklist**:

chore: upgrade travis-deploy-once dependency

---

src/config/rollup.config.js

**What**:
UMD build of dom-testing-library is broken: https://github.com/kentcdodds/dom-testing-library/issues/251
**Why**:
When there are no externals, [this pattern](https://github.com/kentcdodds/kcd-scripts/commit/ad1826ec6bbb4c0c75e45471504e4951696ffded#diff-a1cfe028f2f056e2d30db017481d4ad0R90) reduces to `/^()($|\/)/` which matches any absolute path e.g. `/Users/admin/.../dom-testing-library/src/get-queries-for-element.js`
**How**:
Only match the regex when there is more than 0 externals.
**Checklist**:

fix(rollup): properly handle no externals

---

src/config/babelrc.js

**What**:
don't throw error about @babel/runtime if i'm not using build
**Why**:
If i'm not using `kcd-scripts build` then it shouldn't throw an error about @babel/runtime (i.e. if i'm only using it for tests)
**How**:
added a check for `!isTest`
**Checklist**:
Closes #86

only warn about @babel/runtime for tests

---

package.json

**What**:
add typing for jest
**Why**:
for resolving/autocomplete function, etc for jest in IDE
**How**:
by adding @types/test
**Checklist**:

add types for jest

---

.travis.yml
package.json
src/scripts/__tests__/__snapshots__/travis-after-success.js.snap
src/scripts/travis-after-success.js

BREAKING CHANGE: Requires Node 10.13+
https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0
> Require Node.js >= 10.13

chore: Update semantic-release

---

.travis.yml
package.json
src/scripts/__tests__/__snapshots__/travis-after-success.js.snap
src/scripts/travis-after-success.js

`semantic-release@17` also needs `node@>=10.18`
https://github.com/semantic-release/semantic-release/releases/tag/v17.0.0

Use semantic-release@17 in travis-after-success

---

src/scripts/build/babel.js

feat: Support TypeScript in babel build

---

README.md

**What**: Add [Rollpkg](https://github.com/rafgraph/rollpkg) to the Other Solutions section
**Why**:
Rollpkg is a convention over config build tool to create packages with Rollup and TypeScript. I recently created Rollpkg while converting some packages to TypeScript, and since you're also moving packages to TS I thought you might find it useful.
Rollpkg uses the TS compiler instead of Babel to compile to `ES5` (or your desired target), but it also uses `babel-plugin-annotate-pure-calls`, and I think it should be possible to add support for `babel-plugin-macros`, or maybe some sort of TypeScript macros? Collaborators welcome.
**Checklist**:

Add Rollpkg to other solutions

---

src/config/babelrc.js

https://github.com/browserslist/browserslist#full-list

feat(babelrc): update browsersConfig

---

package.json

**What**: Resolves #237.
Pin `browserslist` anc `caniuse-lite`.
**Why**: Resolves #237. 
**How**: Pinning in `package.json` and using `overrides`.
**Checklist**:

chore(packages): pin browserslist and caniuse-lite versions

---

README.md

Closes #240 
**What**: 
docs: Add an alternative script bebbi-scripts
**Why**:
We wanted a tsc-driven version of kcd-scripts
**How**:
Just a docs addition
**Checklist**:

docs: Add bebbi-scripts
