kentcdodds/kcd-scripts

.all-contributorsrc, README.md, package.json, src/config/lintstagedrc.js
**What**:
Fix a bug on windows related to `lint-staged` config.
**Why**:
On windows, this happens when trying to run lint-staged:
```
λ git commit
husky > npm run -s precommit (node v8.5.0)
25l[08:47:32] Running tasks for **/*.+(js|json|less|css|ts) [started]
[08:47:32] Running tasks for .all-contributorsrc [started]
[08:47:32] Running tasks for .all-contributorsrc [skipped]
[08:47:32] → No staged files match .all-contributorsrc
[08:47:32] C:\Program Files\nodejs\node.exe E:\Projects\repos\glamorous\node_modules\kcd-scripts\dist\index.js format [started]
[08:47:32] C:\Program Files\nodejs\node.exe E:\Projects\repos\glamorous\node_modules\kcd-scripts\dist\index.js format [failed]
[08:47:32] → C:\Program could not be found. Try `npm install C:\Program`.
[08:47:32] Running tasks for …
```
=> fix(config): Use named bin in lintstagedrc.js

.all-contributorsrc, README.md, src/index.js
**What**:
Fixes a bug in `cross-spawn` invocation - #4
**Why**:
Passing `undefined` values in `env` breaks npm.
**How**:
Filter and reduce `process.env` before passing to `cross-spawn`.
**Checklist**:
Closes #4. I will also follow up with `cross-spawn`.
=> fix: Filter undefined values from process.env before spawn

CONTRIBUTING.md, src/config/__tests__/lintstagedrc.js, src/config/lintstagedrc.js, src/scripts/precommit/index.js, src/utils.js
**What**: This adds opt-out capability for autoformatting
**Why**: Because some folks don't want the autoformatting when they're committing code...
**How**: refactor the opt logic and add some tests to cover that.
**Checklist**:
=> feat: add opt-out capability for the auto-formatting

.all-contributorsrc, README.md, src/__tests__/utils.js, src/utils.js
**What**:
Fixing issue with `hasAnyDep` function in utils
**Why**:
When checking to see if one of an array of dependencies is in the package.json, only the first dependency is actually checked. For me, this caused an issue with the Jest configuration. It's supposed to set the `testEnvironment` config value to `jsdom` if one of `['webpack', 'rollup', 'react']` exists, but it only ends up checking for `webpack`. I don't have that dependency and so it incorrectly sets `testEnvironment` to `node` even though I have `react`.
**How**:
`hasAnyDep` was incorrectly spreading the array to the `hasPkgSubProp` function, which is expecting just a single array argument. This ends up only checking the first item in the array. The fix in this PR is to no longer spread the array.
**Checklist**:
=> fix: correctly identify if one of many dependencies is specified

src/run-script.js
**What**:
Fix bug in usage message on windows.
**Why**:
```
λ node src\index.js
Usage: E:\Projects\repos\kcd-scripts\src\index.js [script] [--flags]
Available Scripts:
E:/Projects/repos/kcd-scripts/src/scripts/
E:/Projects/repos/kcd-scripts/src/scripts/build
E:/Projects/repos/kcd-scripts/src/scripts/contributors
E:/Projects/repos/kcd-scripts/src/scripts/format
E:/Projects/repos/kcd-scripts/src/scripts/lint
E:/Projects/repos/kcd-scripts/src/scripts/precommit
E:/Projects/repos/kcd-scripts/src/scripts/test
E:/Projects/repos/kcd-scripts/src/scripts/travis-after-success
E:/Projects/repos/kcd-scripts/src/scripts/validate
Options:
All options depend on the script. Docs will be improved eventually, but for most scripts you can assume that the args you pass will be forwarded to the respective tool …
```
=> fix(usage): Fix available scripts message on Windows

src/__tests__/index.js, src/scripts/__tests__/validate.js
This fixes the tests which are failing on Windows:
- [`src\__tests__\index.js`] `format › calls node with the script path and args`
- [`src\scripts\__tests__\validate.js`] `validate › allows you to specify your
own npm scripts`
<details>
<summary>verbose test output</summary>
```
[test]  FAIL  src\__tests__\index.js
[test]   ● format › calls node with the script path and args
[test]
[test]     expect(value).toMatchSnapshot()
[test]
[test]     Received value does not match stored snapshot 1.
[test]
[test]     - node <PROJECT_ROOT>/src/scripts/test.js --no-watch
[test]     + node E:\Projects\repos\kcd-scripts\src\scripts\test.js --no-watch
[test]
[test]       at Object.<anonymous> (src/__tests__/index.js:44:49)
[test]       at Object.cb (node_modules/jest-in-case/index.js:40:20)
[test] …
```
=> test: Fix failing tests on Windows

src/config/rollup.config.js
Prior to this, setting BUILD_FILENAME_PREFIX would always cause
filenamePrefix to evaluate to 'preact/' since we would evaluate the
lefthand side of the expression for truthiness rather than existence,
causing it to read as
```js
(BUILD_FILENAME_PREFIX || isPreact) ? 'preact/' : ''
```
instead of 
```js
BUILD_FILENAME_PREFIX || (isPreact ? 'preact/' : '')
```
=> fix(config): Ensure env var BUILD_FILENAME_PREFIX is respected

src/config/babelrc.js
fixes #32
**What**:
`loose` mode for babel transforms
**Why**:
shorter, more optimized output code
**Checklist**:
=> feat(babel): use loose mode

src/config/babelrc.js
If a library doesn't check its propTypes at runtime (and imho it shouldnt) then this is a safe optimization that can reduce bundle sizes a little bit.
=> feat(babel): Wrap propTypes for better production DCE

package.json, src/config/rollup.config.js, src/index.js, src/scripts/build/rollup.js, src/utils.js
This is a quick proof of concept, although this cannot be merged as is. Problem with this approach is that we'd have to know all possible keys upfront and pass their values to builds, otherwise they won't get replaced.
What can be done:
- standardize few keys and fill in their default in the config if they are not specified explicitly
- allow for extra keys (but they will suffer from the issue mentioned above)
WDYT?
=> Add rollup-plugin-replace

package.json, src/config/rollup.config.js, src/run-script.js, src/scripts/build/rollup.js, src/utils.js
**What**:
Allow for multiple inputs (with glob pattern) to be passed to rollup script, use `experimentalCodeSplitting` to bundle them in such case.
This dedupes common dependencies, if I use both:
```js
import rtlCssJs from 'rtl-css-js'
import { propertyValueConverters } from 'rtl-css-js/core'
```
I won't end up with duplicated code responsible for `propertyValueConverters`.
**Checklist**:
How I plan to use it can be seen [here](https://github.com/Andarist/rtl-css-js/commit/97bbf55e68aa27f5b79a14845ff8a6375ff45a0f). I've developed this feature because of it, and Ive tested it locally on that commit by `npm link`ing
=> feat(rollup): Use code-splitting with multiple inputs

package.json, src/config/babelrc.js
**What**:
make the `browsers` option of `babel-preset-env` could be overridden by the user.
**Why**:
This request has been described in #43 in detail.
**How**:
leverage the `loadConfig()` method of `browserslist`.
**Checklist**:
I have created a demo project to test this. It works, write tests for this is too hard, I have no idea ...
=> feat(babel): make the config of browserslist could be overrode by user

package.json, src/config/rollup.config.js
**What**:
Enables bundle size snapshots in a `.size-snapshot.json` file
**Why**:
I think it would be really useful to be able to track the bundle sizes, also nice to get this info in PRs that adds third-party libs etc. But it should maybe be a opt-in feature?
**How**:
Just add the `rollup-plugin-size-snapshot` to `rollup.config.js`
**Checklist**:
=> feat(rollup): Add size snapshot plugin

src/config/rollup.config.js, src/scripts/build/rollup.js
**What**:
Don't generate a `.size-snapshot.json` file by default
**Why**:
Does not make sense for libraries like `react-testing-library` and other non browser related libs to generate this file
**How**:
Hide the functionality behind a `--size-snapshot` flag
**Checklist**:
=> feat: move size-snapshot behind a flag

package.json, src/config/babelrc.js
**What**: feat: support custom node version based on engines (falls back to node version 8).
**Why**: So projects can more easily specifically target the version they need to support.
**How**: Using semver and getting the engines.node property in the package.json to determine the oldest version supported and transpile down to that.
**Checklist**:
=> feat: support custom node version based on engines

README.md, package.json, src/config/babelrc.js
Detects whether `flow-bin` is a dependency on the project, if so it will load the `@babel/preset-flow`-module.
**What**:
In `babelrc.js` we should check if `flow-bin` is a dependency and then load the `@babel/preset-flow`
**Why**:
We have copied the same away `react` is being detected by using `ifAnyDep`-utility
**How**:
Small change to `babelrc.js`
**Checklist**:
=> Add support for flow in babel

src/config/rollup.config.js, src/scripts/build/rollup.js
**What**: removing `experimentalCodeSplitting` from the rollup config
**Why**: as of rollup 1.0.0, the functionality provided by `experimentalCodeSplitting` is always active.  The option has been removed and now throws a warning when part of the rollup config.
**How**: removed the `experimentalCodeSplitting` from `src/config/rollup.config.js`
**Checklist**:
=> fix(rollup): remove experimentalCodeSplitting from config

src/__tests__/utils.js, src/utils.js
**What**: fixes #8
**Why**: Developers using windows could not run build using the --bundle flag because of the way windows resolves bins. This was blocking some devs on my team from adopting kcd-scripts.
**How**: by returning early when pathFromWhich resolves a .cmd file (only happens on windows environments)
**Checklist**:
- [x ] Tests
- [x ] Ready to be merged
=> fix(resolveBin): windows will resolve to .cmd binaries if available (#8)

src/config/lintstagedrc.js
As discussed in https://github.com/testing-library/vue-testing-library/pull/86#discussion_r314949006, I'm adding support for `.vue` files in your `pre-commit` hook.
Offering full support for Vue would require several other modifications, but it feels out of the scope (at least for now - happy to help if I'm mistaken). Lint-staged was the only piece I couldn't get up and running.
Thanks for this! 🙌
=> Add support for vue files

src/__tests__/__snapshots__/index.js.snap, src/__tests__/index.js, src/run-script.js
…e running
**What**:
A small change has been made to the `run-script`-file to allow it to pass node arguments.
**Why**:
Currently you are not able to debug unit tests when running `kcd-scripts run test` this change will allow you to pass the `--inspect-brk`-argument so that breakpoints work.
**How**:
Now the script doesn't assume that the first argument is the command to be ran. Instead it will dig up the whitelisted commands from the arguments list and accordingly keep track of node arguments so they can be passed along when spawning the process
**Checklist**:
I am not sure if we want to document this?
=> feat: Allow debugging kcd-scripts for allow debugging unit tests

src/config/jest.config.js
**What**:
Let Jest ignore `__fixtures__` & `__tests__/utils` too
**Why**:
- I think `__fixtures__` is more commonly used, since it's more in line with `__mocks__` & `__tests__`
- `utils` is evenly common to `helpers` I think
**How**:
Expand the ignore array
**Checklist**:
- [N/A] Documentation
- [N/A] Tests
=> Let Jest ignore __fixtures__ & __tests__/utils too

src/config/babelrc.js
BREAKING CHANGE: Requires Node 10.13+
People who rely on the default behaviour (having no `engines.node` key in their `package.json`), will now have compiled source for Node 10.13 instead of 8.
=> chore: Update default Node version for Babel

.huskyrc.js, husky.js, package.json, src/config/huskyrc.js, src/config/index.js
If this one's merged, people could use the following `.huskyrc.js`:
```js
module.exports = require('kcd-scripts/husky');
```
instead of
```js
module.exports = {
hooks: {
'pre-commit': 'kcd-scripts pre-commit',
},
}
```
=> Expose husky config

src/scripts/__tests__/__snapshots__/validate.js.snap, src/scripts/__tests__/validate.js, src/scripts/validate.js
**What**:
Fix a bug in the `validate` script.
**Why**:
The `validate` script currently assumes *at least* one script will be run, however I ran into an edge case where no scripts should be run which results in an error as `concurrently` is spawned without any script arguments.
The particular edge case in which I came across this issue:
- The `validate` script is being spawned from the `pre-commit` script
- The package in which the scripts are run has no `build` or `flow` script defined in its `package.json`
**How**:
Only spawn `concurrently` if more than `0` scripts are queued to run.
**Checklist**:
=> Handle edge case in validate script

README.md, package.json, src/config/babelrc.js, src/config/rollup.config.js, src/utils.js
Closes #130
**What**:
Allow building TypeScript files with `kcd-scripts build --bundle` command.
Also, I've changed the default for babel's `runtimeHelpers` to `hasAnyDep('@babel/runtime')` and I'm not entirely sure why this is needed.
**Why**:
TypeScript is awesome and we want to use it in @testing-library source code.
More in #130 and https://github.com/testing-library/dom-testing-library/issues/494
**How**:
1. Detect if project is using TypeScript by checking for `typescript` dependency and `tsconfig.json` file in root directory.
2. If TS was detected, add `@babel/preset-typescript` to default babel configuration.
3. If TS was detected, add `.ts` and `.tsx` file extensions to default rollup configuration.
4. If TS was detected, support `src/index.ts` and `src/index.tsx` entry files. …
=> Implement TypeScript support

README.md, src/config/lintstagedrc.js
**What**
For TypeScript projects, developers would like to verify that their .ts and .tsx files compile in the lint-staged stop by running
tsc -noemit
`Format`, `lint` and `test` were running on .ts and .tsc files, but nothing was checking that TypeScript code compiled correctly.
**Why**
Enable safer Typescript development
**How**
Used ifTypeScript from utils to check if TypeScript is enabled.
If enabled, run tsc --noEmilt on all .ts and .tsx files
I ran tests with a local project, but did not see a good way to test within this project. If you have ideas, let me know and i'll implement them.
=> run `tsc -noemit` on Typescript files during lint-staged

README.md, src/config/lintstagedrc.js, src/scripts/pre-commit.js
**What**:
Currently, there is a bug in the lint-staged configuration: It checks if `ifTypescript` is truthy. Since this is a function, it will be truthy for every project. I changed the pre-commit script to move typescript compilation from lint-staged to building the whole project during pre-commit.
**Why**:
This is a follow-up on #141 and https://github.com/testing-library/dom-testing-library/pull/572. Currently, it tries to build dom testing library as a typescript project even though it is not one (it doesn't even have typescript as a dependency). This is wrong in my opinion since the reason for the ts build there is that they want to check the typescript definitions. This is already done by dtslint.
**How**:
I removed the lint-staged command for building typescript and added a …
=> fix: Only build typescript files in pre-commit for typescript projects

src/config/babelrc.js, src/config/jest.config.js
Migrating the build tools for `@testing-library/preact` to `kcd-scripts` for consistency among other testing library packages but I encountered some linting + testing issues. I think these should fix it. I tried testing locally via `npm link` but I was getting an error (`Environment key "jest/globals" is unknown`) from `esling-config-kentcdodds` and some strange modules missing errors that may be related to `npm link`.
Ref: https://github.com/testing-library/preact-testing-library/issues/24
=> fix: use jsdom jest environment and h jsx pragma for preact

src/config/babelrc.js
My bad @kentcdodds, `preact-compat` was used for version `8.x` which has now moved to `preact/compat`. So we can't check if the `compat` package is being used but I just replaced it with `react` which should do the trick.
=> fix: set correct jsx pragma for preact/compat

src/config/huskyrc.js
**What**:
- Make the pre commit hook work on windows
- The problem was that the path had backslashes in it and the pre-commit hook thought this was a regex. A path "C:\dev\repo\foo\husky.cmd" was translated to "C:devrepofoohusky.cmd", making that the cmd couldn't be found.
**Why**:
- I encountered problems with it in Dom Testing Library
**How**:
- Wrap the path between quotes 
**Checklist**:
=> fix: precommit hook on windows

README.md, package.json, shared-tsconfig.json, src/__tests__/__snapshots__/index.js.snap, src/run-script.js, src/scripts/build/babel.js, src/scripts/build/rollup.js, src/scripts/pre-commit.js, src/scripts/typecheck.js, src/utils.js
**What**: auto-generate TypeScript definitions and add typecheck script
**Why**: To improve TypeScript support for packages using `kcd-scripts`. I think this is the last missing piece.
**How**: Update build (both babel and rollup) to add a `tsc` script to build the definitions.
**Checklist**:
=> feat(TS): auto-generate TypeScript definitions and add typecheck script

src/__tests__/utils.js, src/scripts/build/babel.js, src/scripts/build/rollup.js, src/utils.js
**What**: Create definition files into the provided --out-dir 
**Why**: Because definitions were always saved into `dist` folder. In @testing-lirabry/react-hooks we are using `lib` as out dir
**How**:
**Checklist**:
=> fix: create definition files into provided folder

src/scripts/build/babel.js
**What**: Remove  `--no-ts-defs` before using babel
**Why**: Because `--no-ts-defs` doesn't exist in babel 
**How**:
**Checklist**:
=> fix: remove --no-ts-defs before using babel

src/config/babelrc.js
**What**:
Preserve function names when eliminating dead code in tests to enable nicer stack traces when errors occur.
**Why**:
Fixes #188
**How**:
I used the `isTest` flag to enable [the `keepFnName` option of `babel-plugin-minify-dead-code-elimination`](https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-dead-code-elimination#options).
**Checklist**:
=> fix(babel): keep function names to improve stack traces in tests

src/config/babelrc.js
Hey Kent,
the idea is simple that we should use ifAnyDep check to decide if use babel-plugin-transform-inline-environment-variables, no?
=> feat: check react/preact for the use of plugin

src/config/rollup.config.js
**What**:
If you want to use workspaces the current `commonjs`-plugin configuration cause rollup not to find all the packages. The change in this commit tries to resolve this. 
**Why**:
If you are using `kcd-scripts` together with `yarn` and try to use workspaces it won't be able to find the `node_modules` directory in  all occasions this makes it more flexible by using a regular expression. 
This change should then also catch references to ../../node_modules in yarn workspaces.
**How**:
I have updated the configuration for the `commonjs`-plugin of rollup
**Checklist**:
=> feat: improve workspaces support

src/run-script.js, src/scripts/__tests__/__snapshots__/test.js.snap, src/scripts/__tests__/test.js, src/scripts/__tests__/validate.js, src/scripts/test.js, src/scripts/validate.js
**What**:
Fixes https://github.com/kentcdodds/kcd-scripts/issues/194.
Replaces dash characters (`-`) from `SCRIPTS_` environment variables with `_`.
In practice `SCRIPTS_PRE-COMMIT` is now `SCRIPTS_PRE_COMMIT`.
**Why**:
Bash does not support environment variables with dash characters (`-`).
This cannot be reproduced with git-bash on windows but appears in Debian 10.
**How**:
When `SCRIPTS_` environment variables are added replace all dashes with underscores. 
Searched and checked all usage of `parseEnv` and `process.env`.
**Checklist**:
**Manual test:**
Without this fix I was unable to pass pre-commit hook of this repository. With the fix applied pre-commit hook runs successfully.
=> fix: remove dash from environment variables

package.json, src/__tests__/index.js, src/scripts/__tests__/format.js, src/scripts/__tests__/helpers/serializers.js, src/scripts/__tests__/lint.js, src/scripts/__tests__/precommit.js, src/scripts/__tests__/test.js, src/scripts/__tests__/validate.js
Now that https://github.com/ikatyang/jest-snapshot-serializer-raw/pull/65 is implemented, we don't need our own version anymore
=> chore: use jest-snapshot-serializer-raw/always as unquoteSerializer

jest.config.js, package.json, src/config/jest.config.js
BREAKING CHANGE: snapshots will now be serialized by 'jest-snapshot-serializer-raw/always'
=> feat: add 'jest-snapshot-serializer-raw/always' as default snapshotSerializer

package.json
**What**:
Closes https://github.com/kentcdodds/kcd-scripts/issues/209
**Why**:
To unblock development
**How**:
Disable `import/no-import-module-exports` until https://github.com/benmosher/eslint-plugin-import/pull/2099 is released
**Checklist**:
- ~[ ] Documentation~
=> test: Temporarily disable import/no-import-module-exports

src/config/jest.config.js
**What**: Use `modulePaths` to improve Jest 27 imports
**Why**: Fixes #219 which would unblock https://github.com/testing-library/eslint-plugin-jest-dom/pull/185
**How**: 
- Moved all `moduleDirectories` (except `node_modules`) to `modulePaths`, which properly prioritizes resolving `node_modules` over local project modules
- It's theoretically possible that this could break a test that relies on the opposite functionality, though IMO that would not be a good assumption to make, and it's worth noting that semver does not protect users from breaking changes resulting from bug fixes
- Switched to using `<rootDir>`, which should provide better support for `kcd-scripts test` in monorepos
- Ran an end to end test using `npm link` within …
=> fix: use `modulePaths` to improve Jest 27 imports

src/config/jest.config.js
**What**: a string into an array
**Why**: it breaks jest otherwise, fixes a regression from #220
**How**: added `[` and `]`
**Checklist**:
=> Fix `setupFilesAfterEnv`: must be an array

.npmrc
**What**: updated npm repo link to use https instead of http
**Why**: as of October 4th 2021 use of TLS 1.0 and TLS 1.1 is not supported, hence http://registry.npmjs.org/ can't be used. Instead we have to use https://registry.npmjs.org/
**How**: updated link in .npmrc 
**Checklist**:
=> updated npm repo to https://registry.npmjs.org/

src/config/prettierrc.js
**What**: Rename `jsxBracketSameLine` to `bracketSameLine`
**Why**: Prettier prints deprecation warnings when using `jsxBracketSameLine`
> This release renames the `jsxBracketSameLine` option to `bracketSameLine`, which supports HTML, Vue, and Angular in addition to JSX. The old name has been deprecated.
> https://prettier.io/blog/2021/09/09/2.4.0.html
**How**: Edited Prettier config
**Checklist**:
=> fix(prettier): jsxBracketSameLine -> bracketSameLine

.github/workflows/validate.yml, package.json, src/__tests__/__snapshots__/index.js.snap, src/__tests__/__snapshots__/utils.js.snap
BREAKING CHANGE: Drops support for Node.js 12x. Updates Jest to 29.x
Needs update for required GH checks (since 12.x is no longer tested)
**What**:
Drops support for Node.js 12x. Updates Jest to 29.x
**Why**:
Updating Jest to 29.x pulls in JSDOM 20.x which no longer supports Node.js 12.x
**How**:
Bump dependencies from the Jest monorepo and update snapshots
**Checklist**:
=> Bump Jest to 29.x and drop support for Node.js 12.x

src/config/babelrc.js
**What**: Preact build doesn't work due to incorrect Preact imports
**Why**:  downshift is not working with preact
**How**: I had to go through the build process and change import alias from "preact" to "preact/compat"
**Checklist**:
Steps I followed to test:
1. Made the alias change for kcd-scripts in downshift node_modules
2. I ran the build and copied preact build output in a sample preact app
3. It started working :)
Downshift issues related to this:
1. https://github.com/downshift-js/downshift/issues/1430
2. https://github.com/downshift-js/downshift/issues/1198
=> Fix: Preact build doesn't work due to incorrect Preact imports

src/__tests__/utils.js, src/utils.js
**What**:
Set build output file extension by target format.
**Why**:
https://github.com/testing-library/react-testing-library/issues/1338
I looking for a solution to this issue.
First of all, the issue was different from `testing-library/dom`, which is referred to in `testing-library/react`, and `testing-library/dom`, which is referred to in `testing-library/user-event`.
So I solved this problem by changing the extension of the esm file to `.mjs`.
`testing-library` was using that library as a build tool, and found out that within that library they were building extensions as fixed as `.js` and are trying to fix it.
After configure in `testing-library/react`, but `getConfig().eventWrapper` in `testing-library/user-event` is default function.
After configure in `testing-library/react`, so …
=> fix(utils): setup extension by format in getRollupOutput (maybe breaking-change)
